language: rust
rust:
  - stable
matrix:
  fast_finish: true
cache: cargo
services:
  - mysql
  - redis-server
env:
  global:
    - AUTH_SALT=CHANGEME
    - DATABASE=mysql
    - DATABASE_URL=mysql://root:root@0.0.0.0:13306/rust-actix-framework
    - JWT_EXPIRATION=24
    - JWT_KEY=4125442A472D4B614E645267556B58703273357638792F423F4528482B4D6251
    - REDIS_URL=127.0.0.1:6379
    - RUST_BACKTRACE=1
    - RUST_LOG="actix_web=info,actix_server=info,actix_redis=trace"
    - SERVER=127.0.0.1:3000
    - SESSION_KEY=4125442A472D4B614E645267556B58703273357638792F423F4528482B4D6251
    - SESSION_NAME=auth
    - SESSION_SECURE=false
    - SESSION_TIMEOUT=20
before_script:
  - sudo apt-get update
script:
  - cargo build --verbose --all
  - SERVER=127.0.0.1:3000
  - cargo test --verbose --all
before_install:
  - mysql -e 'CREATE DATABASE rust-actix-framework;'