version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rust-actix-framework
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    expose:
      - "3306"

volumes:
  db_data: {}
