version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rust-axum-framework
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    expose:
      - "3306"
  #  wordpress:
  #    depends_on:
  #      - db
  #    image: wordpress:latest
  #    ports:
  #      - "8000:80"
  #    restart: always
  #    environment:
  #      WORDPRESS_DB_HOST: db:3306
  #      WORDPRESS_DB_USER: wordpress
  #      WORDPRESS_DB_PASSWORD: wordpress
  #      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
